// export const ARROW_REMOVAL_DELAY_MS = 500;
export const ARROW_REMOVAL_DELAY_MS = 200;
export const GAME_START_COUNTDOWN_INTERVAL_MS = 1000;
export const NAVIGATION_DELAY_MS = 1000;
export const FALLBACK_TIMER_MS = 10000;
export const MATCHMAKING_WAITING_TIMER_INTERVAL_MS = 1000;
