export const ONE_SECOND_MS = 1000;
export const NAVIGATION_DELAY_MS = 1000;
export const FALLBACK_TIMER_MS = 10000;
export const MATCHMAKING_WAITING_TIMER_INTERVAL_MS = 1000;
export const PRE_GAME_COUNTDOWN_SECONDS = 3;
