import type { ChatClientMessage } from '@protocol/domains/chat/client-messages';
import type { ChatServerMessage } from '@protocol/domains/chat/server-messages';
import type { MatchmakingClientMessage } from '@protocol/domains/matchmaking/client-messages';
import type { MatchmakingServerMessage } from '@protocol/domains/matchmaking/server-messages';
import type { GameplayClientMessage } from '@protocol/domains/gameplay/client-messages';
import type { GameplayServerMessage } from '@protocol/domains/gameplay/server-messages';

// Union of all client messages (client → server)
type ClientMessage = ChatClientMessage | MatchmakingClientMessage | GameplayClientMessage;

// Union of all server messages (server → client)
type ServerMessage = ChatServerMessage | MatchmakingServerMessage | GameplayServerMessage;

// Connection identifier (generated by server via UUID)
type ConnectionId = string;

// Handler signature
type DomainHandler<TMessage extends { type: string; payload: unknown }, TContext> = (
  payload: TMessage['payload'],
  context: TContext,
) => void | Promise<void>;

// Handler map with context
type HandlerMapWithCtx<TMessage extends { type: string; payload: unknown }, TContext> = {
  [K in TMessage['type']]: DomainHandler<Extract<TMessage, { type: K }>, TContext>;
};

// Broadcast options for multi-tab support
type BroadcastOptions = {
  excludeConnectionId?: ConnectionId;
};

// WS Bridge interface (what domain ws-effects use)
interface WsBridge {
  broadcast(message: ServerMessage, opts?: BroadcastOptions): void;
  broadcastToRoom(roomId: string, message: ServerMessage, opts?: BroadcastOptions): void;
  sendToUser(userKey: string, message: ServerMessage): void;
  rooms: {
    join(roomId: string, connectionId: ConnectionId): void;
    leave(roomId: string, connectionId: ConnectionId): void;
    getMembers(roomId: string): Set<ConnectionId>;
  };
}

export type {
  ClientMessage,
  ServerMessage,
  ConnectionId,
  DomainHandler,
  HandlerMapWithCtx,
  BroadcastOptions,
  WsBridge,
};
