// Connection identifier (generated by server via UUID)
type ConnectionId = string;

// Handler signature
type DomainHandler<TMessage extends { type: string; payload: unknown }, TContext> = (
  payload: TMessage['payload'],
  context: TContext,
) => void | Promise<void>;

// Handler map with context
type HandlerMapWithCtx<TMessage extends { type: string; payload: unknown }, TContext> = {
  [K in TMessage['type']]: DomainHandler<Extract<TMessage, { type: K }>, TContext>;
};

// Broadcast options for multi-tab support
type BroadcastOptions = {
  excludeConnectionId?: ConnectionId;
};

// WS Bridge interface (what domain ws-effects use)
interface WsBridge<TMessage> {
  broadcast(message: TMessage, opts?: BroadcastOptions): void;
  broadcastToRoom(roomId: string, message: TMessage, opts?: BroadcastOptions): void;
  sendToUser(userKey: string, message: TMessage): void;
  rooms: {
    join(roomId: string, connectionId: ConnectionId): void;
    leave(roomId: string, connectionId: ConnectionId): void;
    getMembers(roomId: string): Set<ConnectionId>;
  };
}

export type {
  ConnectionId,
  DomainHandler,
  HandlerMapWithCtx,
  BroadcastOptions,
  WsBridge,
};
